/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#e4e1e6",
        "on-secondary-fixed": "#0d1c2d",
        "tertiary-fixed": "#dbe1ff",
        "on-primary-fixed-variant": "#920028",
        "surface-container-lowest": "#0e0e11",
        "secondary-fixed": "#d4e4fa",
        "text-muted": "#94A3B8",
        "surface-dim": "#131316",
        "on-surface": "#e4e1e6",
        "tertiary-container": "#2f6af2",
        "on-primary-fixed": "#40000c",
        "background-deep": "#000000",
        "surface-bright": "#39393c",
        "on-tertiary-container": "#fdfaff",
        "surface-container-highest": "#353438",
        "on-background": "#e4e1e6",
        "on-tertiary": "#002a78",
        "on-error": "#690005",
        "surface-tint": "#ffb3b6",
        "surface-container-low": "#1b1b1e",
        "tertiary-fixed-dim": "#b4c5ff",
        "inverse-on-surface": "#303033",
        "primary-fixed-dim": "#ffb3b6",
        "on-error-container": "#ffdad6",
        "secondary-container": "#39485a",
        "surface-container-high": "#2a2a2d",
        "on-secondary-fixed-variant": "#39485a",
        "tertiary": "#b4c5ff",
        "on-tertiary-fixed": "#00174b",
        "on-tertiary-fixed-variant": "#003ea8",
        "inverse-primary": "#be0037",
        "outline-variant": "#5c3f40",
        "primary-fixed": "#ffdada",
        "secondary": "#b9c8de",
        "on-secondary": "#233143",
        "surface-zinc": "#18181B",
        "background": "#131316",
        "primary-container": "#e11d48",
        "secondary-fixed-dim": "#b9c8de",
        "on-primary": "#68001a",
        "on-primary-container": "#fffaf9",
        "error": "#ffb4ab",
        "accent-red-bright": "#F43F5E",
        "error-container": "#93000a",
        "surface-variant": "#353438",
        "on-secondary-container": "#a7b6cc",
        "on-surface-variant": "#e5bdbe",
        "surface-container": "#1f1f22",
        "primary": "#e11d48",
        "outline": "#ac8889",
        "surface": "#131316"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "section-gap": "80px",
        "gutter": "24px",
        "margin-mobile": "16px",
        "component-padding": "1.5rem",
        "container-max": "1280px"
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "display-hero": ["Sora", "sans-serif"],
        "headline-lg-mobile": ["Sora", "sans-serif"],
        "headline-lg": ["Sora", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-md": ["Sora", "sans-serif"],
        "label-bold": ["Inter", "sans-serif"]
      },
      fontSize: {
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "label-sm": ["12px", {"lineHeight": "1.2", "fontWeight": "500"}],
        "display-hero": ["72px", {"lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "800"}],
        "headline-lg-mobile": ["32px", {"lineHeight": "1.2", "fontWeight": "700"}],
        "headline-lg": ["48px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-md": ["16px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "headline-md": ["24px", {"lineHeight": "1.3", "fontWeight": "600"}],
        "label-bold": ["14px", {"lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
}
